database:
  host: 127.0.0.1
  port: 3306
  name: mc_server
  username: root
  password: change_me
  parameters: "?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
